### ISSUE TITLE
Full refactoring (restarting)  of the project

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/mimesis#175]
We need to refactor this project. Completely.

Goals:

- [x] Remove useless providers/methods.
- [x] Change the structure of the project.
- [x] Bring the code in compliance with the requirements of PEP8.
- [x] Add/Update documentation.
- [x] Add auto deploy on `PyPi` on tag.
- [x] Add mechanism for uglify json files (this will reduce the file size) only when deploy on `PyPi`, otherwise we can't normally edit json files when will update provider's data.
- [ ] Find and fix bottlenecks in Generic(). Just run [this script](https://gist.github.com/lk-geimfari/045e44aad51881641e5f896256415761) and you'll understand what i talking about.

**Comment by lk-geimfari** [comment]
We will try to do this all by the end of the summer, given that we only work on this project on weekends.

**Comment by sobolevn** [comment]
I also advise you to add `flake8`. Must have plugins:
1. `flake8-builtins`
2. `flake8-commas`
3. `flake8-quotes` (my fav)
4. `isort` (not actually a `flake8`-plugin

Here's the full list: https://github.com/sobolevn/django-split-settings/blob/master/setup.py#L26

**Comment by sobolevn** [comment]
About your points. 

 1. Remove useless providers/methods.
Which ones do you consider useless? Are you sure that *noone* uses it?
 
2. Change the structure of the project.
++

3. Bring the code in compliance with the requirements of PEP8.
++

4. Add/Update documentation.
++

5. Add auto deploy on PyPi on tag.
++

6. Add mechanism for uglify json files (this will reduce the file size).
++ 

7. Add mechanism for inflect Russian first, last, and middle names (great example is petrovich). We can realize this like a decorator, maybe.
I guess this should be done separately. Do still want to have no dependencies?

**Comment by lk-geimfari** [comment]
@sobolevn I think that `json()` method of `Structure()` is too specific and useless. I think that point 7 is not best idea. We do not need dependencies. I'll update goals.

**Comment by sobolevn** [comment]
- Type hint everything ?

**Comment by Valerievich** [comment]
Few questions about "Bring the code in compliance with the requirements of PEP8 (flake8, pycodestyle)":
1. Should we check only ```*.py``` files or ```*.json``` too?
2. There are a lot of F401, F403, F405 errors (produced Flake8). It's because of `from somemodule import *`. Is it better to ignore these errors?

**Comment by lk-geimfari** [comment]
@Valerievich 

1. We should always ignore `data/*` because in data/ we store only data, not code of elizabeth.
2. Ignore.
2. Poin 1. We ignore int/, because is data.

**Comment by Valerievich** [comment]
In /test_data/test_generic.py we have:

```python
def test_bad_argument(generic):
    with pytest.raises(AttributeError):
        result = generic.bad_argument
```

This causes `F841 local variable 'result' is assigned to but never used`

Is this wrong code? Have I to add an assert?

**Comment by lk-geimfari** [comment]
@Valerievich  You can replace `result` with `__`

**Comment by Valerievich** [comment]
How to understand which providers/methods are useless (it's about first task of list)? Are there conditions?

**Comment by lk-geimfari** [comment]
@Valerievich for example `json()` of `Structured()`. It was bad idea to get data for them using `Personal()`. Try to replace it with random json generator.

**Comment by Valerievich** [comment]
@lk-geimfari Should there be clear data? Or is it possible to generate data smth like 
```{'key1': value1, 'key2': value2 ...}``` ?

**Comment by lk-geimfari** [comment]
@Valerievich Actually useful `json()` generator was been already created by @wikkiewikkie. It was a mistake to propose him to replace that method with a new one. Here you can look at old implementation of `json()`. [Use it](https://github.com/wikkiewikkie/elizabeth/blob/deec4921ed96454dd583e735abe876ea88102405/elizabeth/core/elizabeth.py#L478). Just refactor. Also [here](https://github.com/lk-geimfari/elizabeth/pull/106/commits/e3dde32ff5883b33a1289ca84a45b344aa0b4396) you can find tests of this implementation.

**Comment by Valerievich** [comment]
I've done with Structured(). Is it necessary to remove another Providers or methods? I can help.

**Comment by lk-geimfari** [comment]
@Valerievich Actually you can help us with much important thing.  If you are use PyCharm you can find TODO list. This task is very important.

For example: https://github.com/lk-geimfari/elizabeth/blob/feature-new-strucutre/tests/conftest.py#L56

`Text()` is international provider (i.e support all locales), but at this moments we test only default locale (default locale is `en`).

Help us with tasks in TODO. All the main work needs to be done in a new branch: [feature-new-strucutre](https://github.com/lk-geimfari/elizabeth/blob/feature-new-strucutre/).

**Comment by Valerievich** [comment]
ToDo "Resolve importing errors and use importing format as above" is secret for me. Can't resolve importing errors. Where should I look? Any ideas?

**Comment by sobolevn** [comment]
@Valerievich what's your exact problem? What kind of import errors do you have?
Could you please provide more information?

**Comment by Valerievich** [comment]
I try to use following import format 
```from mimesis.providers import Games``` in ```generic.py```

and then get this:
[tr.txt](https://github.com/lk-geimfari/mimesis/files/1156355/tr.txt)

**Comment by lk-geimfari** [comment]
@Valerievich I get similar error. I don't know why it's happens, but we really need to fix it.

**Comment by sobolevn** [comment]
@Valerievich could you please try this:

```python
from mimesis.providers.games import Games
from mimesis.providers.hardware import Hardware
```

Instead of: 

```python
# TODO: Resolve importing errors and use importing format as above.
from .games import Games
from .hardware import Hardware
```

**Comment by Valerievich** [comment]
@sobolevn  I tried this way. Import worked well in this case. But @lk-geimfari wants to use format exactly like ```from mimesis.providers import Games```. There are not any problem with import other providers in ```generic.py``` e.g. ```Address``` .

**Comment by Valerievich** [comment]
@lk-geimfari I've resolved that import problem issue in new PL #198 
Please check it.

**Comment by lk-geimfari** [comment]
@Valerievich I like how it's looks. Let's wait opinion of @sobolevn. Are we have any reasons to don't use this importing format?

**Comment by Valerievich** [comment]
@lk-geimfari No, we dont.

**Comment by lk-geimfari** [comment]
I have added json minify, but the result is quite the opposite of what I expected. The size of the project even increased from [6.8 Mb](url) to `7.2 Mb`. If no one has any idea why this happens, then I suggest removing the minifer.

**Comment by Valerievich** [comment]
@lk-geimfari why do you think it's unacceptable ? 0.4Mb is not a big increase I think.

**Comment by lk-geimfari** [comment]
@Valerievich The goal was to reduce the size of the project, by minimizing the JSON files, but it worked exactly the opposite. What is a reason to minimizing of JSON files if the size of the project was only become larger? Don't you agree?

**Comment by lk-geimfari** [comment]
@Valerievich `6.8 Mb` is size before minimize and `7.2 Mb` is size after minimize.

**Comment by Valerievich** [comment]
I think `'Add/Update documentation.'` is done.

**Comment by lk-geimfari** [comment]
@Valerievich It's still do not work: http://mimesis.readthedocs.io/en/latest/api.html#cryptographic. I don't know why.

**Comment by Valerievich** [comment]
How did you create this version? All that necessary is go to `/docs` and exec. `make html`. 
I've pulled `master` branch recently and it works for me.

<img width="692" alt="screen shot 2017-09-11 at 12 57 21 pm" src="https://user-images.githubusercontent.com/12416731/30269255-e1416a70-96f0-11e7-94c3-7e22c69b6995.png">

**Comment by lk-geimfari** [comment]
@Valerievich It's created automatically by ReadTheDocs. I'll try to do it manually.

**Comment by sobolevn** [comment]
I have faced some issues while using `rtd`. Check its logs and configs.

**Comment by lk-geimfari** [comment]
@sobolevn Seems like i have incorrectly configured rtd. I'll fix it tonight.

**Comment by lk-geimfari** [comment]
@sobolevn Do you have an account on rtd? Can i add you to maintainers on rtd?

**Comment by sobolevn** [comment]
@lk-geimfari sure, mail@sobolevn.me

**Comment by lk-geimfari** [comment]
@sobolevn Please, check out your rtd account. I have added you to maintainers. Thank you!

**Comment by lk-geimfari** [comment]
@sobolevn And i have deleted your answer above, because sometimes people grab emails on github for spamming.

**Comment by lk-geimfari** [comment]
@sobolevn Can you look at settings on the ReadTheDocs, please. I don't undersand why, but on my local machine and in rtd the documentation generates without API Refernce. Thanks!

**Comment by Valerievich** [comment]
`Find and fix bottlenecks in Generic(). Just run this script and you'll understand what i talking about @Valerievich.`. 
I think this is a result of call `def seed()` from `random.Random`. We call it from our custom Random() class in `helpers.py`. I think it's not a good idea to change this __init__ method : )

**Comment by andela-ieyo** [comment]
I would love to contribute to this. How do I get involved.

**Comment by lk-geimfari** [comment]
@andela-ieyo Please, look at the last task in TODO. Thanks!

**Comment by CP-NEMO** [comment]
#include<stdio.h>

**Comment by sobolevn** [comment]
Hooray! 🎉

**Comment by lk-geimfari** [comment]
@sobolevn Yeah, we did it! :smile:
